name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.df89a89f-9068-4564-b709-2705a285da1c }}
          GH_TOKEN: ${{ secrets.b1880a026d01bc4e66fd6fa730ac8c3acd02a827 }}
          USERNAME: tao8687
          SHOW_TITLE: true
